<?php
if ($block->getProductTypeId() == 'giftcertificate'): ?>
   
<div class="topgift-banner">
    <img src="https://stage.thehouseofthings.com/media/wysiwyg/top-banner.png" alt="theart-of-gift" border="0">
    <div class="topdec">
        <h1>THE ART <span>of</span><br>GIFTING</h1>
    </div>
</div>
<div class="banner-dec">
    <div class="container">
        <h1>"Gifts to cherish, Memories to inherit."</h1>
        <p>"Heirlooms are more than objects, they are whispers from</br>
            the past, carrying the love of those who came before."</p>
    </div>
</div>


<?php endif; ?>