<div class="contact-box">
    <p><strong>Have a question? Call or Whatsapp us</strong></p>
    <p class="color_chng">Mon-sat &nbsp; - &nbsp; 10 am to 7 pm (ist)</p>
    <p><strong>Customer Care Executive</strong></p>
    <div class="cart_whatsapp">
        <a href="https://wa.me/918003011110" target="_blank">
            <img src="/pub/media/whatsapp-di.png" alt="Whatsapp"> +91 80030 11110
        </a>
    </div>
</div>

<style>
    .contact-box {
      padding: 15px 20px;
      color: #333;
      line-height: 1.5;
      font-size: 14px;
      text-align: left;
    }

    .contact-box p {
      color: #4e4e4d;
    }
    .contact-box p strong {
      font-weight: 500;
    }
    .checkout-cart-index p {
        padding-bottom: 0px !important;
        margin: 0;
    }
    .contact-box .color_chng {
        color: #838483;
    }
    .cart_whatsapp img {
        max-width: 20px;
    }
    .cart_whatsapp a {
        display: flex;
        align-items: center;
        column-gap: 5px;
        font-size: 16px;
        color: #4e4e4d;
        font-weight: 500;
        text-decoration: underline;
    }
    @media screen and (max-width: 767px) {
        .cart-items-container .cart-container .cart-summary .contact-box {
            display: none;
        }
    }
  </style>