<div class="summary_icons_wrap">
    <div class="summary_inner">
        <img src="https://stage.thehouseofthings.com/pub/media/securepayment.png" alt="">
    </div>
    <div class="summary_inner">
        <img src="https://stage.thehouseofthings.com/pub/media/worldwide.png" alt="">
    </div>
    <div class="summary_inner">
        <img src="https://stage.thehouseofthings.com/pub/media/personal-assistance.png" alt="">
    </div>
</div>

<!-- total checkout below section -->

<!-- <div class="contact-section">
  <p>Have a question? Call or Whatsapp us</p>
  <p><strong>Mon–Sat</strong> - 10 am to 7 pm (IST)</p>
  <p>Customer Care Executive</p>
  <p class="whatsapp">
    <span>📱</span> <a href="https://wa.me/918003011110" target="_blank">+91 80030 11110</a>
  </p>
</div> -->

<style>
    .summary_icons_wrap {
        display: flex;
        align-items: center !important;
        column-gap: 20px;
    }

    @media screen and (max-width: 767px) {
        .cart-items-container .cart-container .cart-summary .summary_icons_wrap {
            display: none;
        }
    }
    
</style>