<?php
/**
 * @category Mageants GiftCard
 * @package Mageants_GiftCard
 * @copyright Copyright (c) 2016 Mageants
 * @author Mageants Team <support@mageants.com>
 */

$_item = $block->getItem();
$currencySymbol = $block->getHelperCurrencySymbol();
?>
<?php
$itemCatIds = $_item->getProduct()->getCategoryIds();
$catIncre = 1;
?>
<input type="hidden" name="<?= /* @noEscape */ $_item->getProduct()->getId(); ?>" class=
"categoryids" id="categoryids" 
value='<?php foreach ($itemCatIds as $catid) {
    ?><?= /* @noEscape */ (count($itemCatIds) > $catIncre) ? $catid.",":$catid; $catIncre++;} ?><?php /* @noEscape */ $_item->getRowTotal();  ?>'/>
<?php
if ($_item->getProductType()=='giftcertificate'):
    $giftquote=$block->getNotLoggedInGiftQuoteItems($block->geNotLoggedIntcustomerId());
    $product = $_item->getProduct(); // Get cart product details
    $additional_data = $block->getAdditionalData(); // Get cart product additionl details defined in block page
    $saveQuote=$block->saveQuote($_item->getQuoteId());
    $count=1;
    ?>
        <input type="hidden" id="base-gift-url" value="<?= /* @noEscape */ $block->getUrl(); ?>"/>

        <?php
        foreach ($giftquote as $quote):
            $quote_data =  $quote->getData();
            $productIds = [];
            foreach ($quote_data as $quote_data_value):
                $productIds[] = $quote_data_value['product_id'];
                $productIds_imp = implode(',', $productIds);
                if ($productIds_imp==$product->getId()): ?>
                    <div class="additional-info">
                        <div>
                            <span><?= /* @noEscape */ $additional_data; ?> </span>
                        </div>
                        <div>
                            <span><?= /* @noEscape */ __('Gift Card Value:'); ?>
                                <?= /* @noEscape */ $currencySymbol.$_item->getCustomPrice();?></span>
                        </div>
                        <div>
                            <span><?= /* @noEscape */ __('Gift Card Type:'); ?>
                                <?= /* @noEscape */ $block->getCardType($quote_data_value['card_types']); ?></span>
                        </div>
                        <div>
                            <span><?= /* @noEscape */ __('Gift Card Sender:'); ?>
                                <?= /* @noEscape */ $quote_data_value['sender_name']; ?></span>
                        </div>
                        <div>
                            <input type="hidden" class="quote-id" value=
                            <?= /* @noEscape */ $quote_data_value['id']; ?> />
                            <input type="hidden" name="productid" id="productid" value='
                                <?= /* @noEscape */ $_item->getProduct()->getId(); ?>'/>
                            <a href="javascript:void(0)" class="deletequote">Remove</a>
                        </div>
                        <div class="loading-cart"></div>
                    </div>    
                    <hr/>
                    <?php
                    $count++;
                endif;
            endforeach;
        endforeach;
    endif;
?>
<script>
    require(['jquery','giftcertificate'],function($){
    });
</script>