<?php

// @codingStandardsIgnoreFile

?>

<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */

$productId = $block->getSaleableItem()->getId();

/** ex: \Magento\Catalog\Pricing\Price\RegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** ex: \Magento\Catalog\Pricing\Price\FinalPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_product = $objectManager->get('Magento\Catalog\Model\Product')->load($productId);
$store = $objectManager->get('\Magento\Store\Model\StoreManagerInterface')->getStore();
$currencyCode = $store->getCurrentCurrencyCode();

$new_layout = array(137);
$categories = $_product->getCategoryIds();
$result = array_intersect($new_layout, $categories);
if (empty($result)) { ?>
	<div class="price-on-request-gk-1">
		<div class="">
			<?php
			if ($_product->getData('price_on_request')) {
			?>
				<div class="row price-on-request price-on-request-gk " itemprop="offers" itemscope itemtype="http://schema.org/Offer">
					<h3><?php /* @escapeNotVerified */ echo __('Price on request') ?></h3>
					<p class="por-desc"><?php echo $_product->getData('price_request_desc'); ?></p>
					<meta itemprop="price" content="<?= $_product->getFinalPrice(); ?>" />
					<meta itemprop="priceCurrency" content="<?= $currencyCode ?>" />
				</div>

			<?php
			} else {
			?>
				<?php if ($block->hasSpecialPrice()): ?>
					<span class="special-price">
						<h3 class="red old-price float-R">
							<?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
								'display_label'     => __('Special Price'),
								'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
								'price_type'        => 'finalPrice',
								'include_container' => true,
								'schema' => $schema
							]); ?>
						</h3>
					</span>
					<span class="old-price">
						<h3 class="productPrice">
							<?php /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
								'display_label'     => __('Regular Price'),
								'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
								'price_type'        => 'oldPrice',
								'include_container' => true,
								'skip_adjustments'  => true
							]); ?>
						</h3>
					</span>
				<?php else: ?>
					<?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
						'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
						'price_type'        => 'finalPrice',
						'include_container' => true,
						'schema' => $schema
					]); ?>
				<?php endif; ?>

				<?php if ($block->showMinimalPrice()): ?>
					<?php if ($block->getUseLinkForAsLowAs()): ?>
						<a href="<?php /* @escapeNotVerified */ echo $block->getSaleableItem()->getProductUrl(); ?>" class="minimal-price-link">
							<?php /* @escapeNotVerified */ echo $block->renderAmountMinimal(); ?>
						</a>
					<?php else: ?>
						<span class="minimal-price-link">
							<?php /* @escapeNotVerified */ echo $block->renderAmountMinimal(); ?>
						</span>
					<?php endif ?>
				<?php endif; ?>
			<?php } ?>
		</div>
	</div>
<?php } ?>