<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * @category   BSS
 * @package    Bss_GA4
 * @author     Extension Team
 * @copyright  Copyright (c) 2022-2022 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
/**
 * @var \Bss\GA4\Block\ViewCheckoutIndex $block
 */
$escaper = $block->escaper();
$collection = $block->getCollection();
?>
<?php if ($block->isEnableModule() && $collection): ?>
    <script>
        gtag("event", "begin_checkout", {
            currency: "<?=$escaper->escapeHtml($block->getCurrency())?>",
            value: "<?=$escaper->escapeHtml($block->getValue())?>",
            coupon: "<?=$escaper->escapeHtml($block->getCouponCode())?>",
            items: <?= /** @noEscape  */ $block->serializeItem($collection)?>
        });
    </script>
<?php endif; ?>
