<?php 
/**
 * Olegnax Quickview 
 *
 * @author      Olegnax
 * @package     Olegnax_Quickview
 * @copyright   Copyright (c) 2022 Olegnax (http://olegnax.com/). All rights reserved.
 */
declare(strict_types=1);
use Olegnax\Quickview\Helper\Helper;
$settings = $this->helper(Helper::class)->getConfig('olegnax_quickview', $block->getData('dynamic_store_code'));
$forceoverflow = true;
$maxheight = true;
?>
<script>
    require( [ "jquery", 'underscore' ], function ( $, _ ) {
        "use strict";

        $( function () {
            var parentBody = window.parent.document.body;
            $( '.ox_quickview-preloader', parentBody ).hide();
            $( '#ox_quickview_wrapper iframe', parentBody ).animate( { 'opacity': 1 }, 100 );
            $( '.reviews-actions a' ).attr( 'target', '_parent' );
            $( '.product-social-links a' ).attr( 'target', '_parent' );
			<?php 	if (($settings['general']['hide_tabs'] || (!$settings['general']['hide_tabs'] && $settings['general']['move_tabs'])) && $settings['general']['hide_upsell'] && $settings['general']['hide_related'] && $maxheight){  ?>
            $( 'body' ).addClass('ox-qv-content-maxheight');
				<?php if ($forceoverflow){  ?>
				$( 'body' ).css( 'overflow', 'hidden' );
				<?php } ?>
			<?php } ?>

        } );

        $( 'a[href]:not([href="#"])' ).on( 'click', function ( e ) {
            var $this = $( this ),
                href = $this.attr( 'href' ).replace( /\#.*$/, '' );
            if ( 0 >= href.length || $this.data( 'disable-parent' ) || '_blank' === $this.attr( 'target' ) ) {
                return;
            }
            e.preventDefault();
            top.window.location.href = href;
        } );

        $( 'body' ).on( 'submit', 'form', function ( event ) {
            event.stopPropagation();
            event.preventDefault();
            var parentBody = window.parent.document.body;
            var $uenc = $( this ).find( 'input[name=uenc]' );
            if ( $uenc.length ) {
                $uenc.attr( 'value', ( function b64EncodeUnicode( str ) {
                    return btoa( encodeURIComponent( str ).replace( /%([0-9A-F]{2})/g,
                        function toSolidBytes( match, p1 ) {
                            return String.fromCharCode( '0x' + p1 );
                        } ) ).replace( /\=$/, '' );
                } )( window.parent.location.href ) );
            }
            $( this ).appendTo( parentBody ).trigger( 'submit' );
        } )
    } );
</script>
