<?php $buttonTitle = __('Go To Product');?>
<div class="ox-quickview-gotoproduct__block">
	<div class="actions">
		<a target="_parent" href="<?php /* @escapeNotVerified */ echo $this->getProduct()->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>" class="action primary" id="ox-quickview-gotoproduct__button">
			<span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
		</a>
	</div>
</div>