<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Sales\Block\Order\Email\Items\DefaultItems */

/** @var $_item \Magento\Sales\Model\Order\Item */
$_item = $block->getItem();
$_order = $_item->getOrder();


$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product_order = $objectManager->get('Magento\Catalog\Model\Product')->load($_item->getProductId());
$helperImport = $objectManager->get('\Magento\Catalog\Helper\Image');
$imageUrl = $helperImport->init($product_order, 'product_page_image_small')
                ->setImageFile($product_order->getSmallImage()) // image,small_image,thumbnail
                ->resize(100)
                ->getUrl();
$hsnCode=$product_order->getHsncode();

if( ! ( $hsnCode )){
    $hsnCode =  'N/A';
}   
?> 

    <td class="item-info<?= ($block->getItemOptions() ? ' has-extra' : '') ?>"> 

        <table>
                <tr>
                    <td>
                        <?php if(  $imageUrl ){ 
                            echo '<a style="float: left;" href="'.$product_order->getProductUrl().'"><img src="'.$imageUrl.'" alt="" />'; 
                        } ?>
                    </td>
                    <td> 
                        <div class="content-item" style="float: left; padding-left:12px;"> 
                            <p class="product-name"><a  href="<?php echo  $product_order->getProductUrl();?>"><?= $block->escapeHtml($_item->getName()) ?></a></p>
                            <p style="text-align:left;" class="hsn" ><?php echo "HSN CODE:".$hsnCode; ?></p> 
                            <?php if ($block->getItemOptions()) : ?>
                                <dl class="item-options">
                                <?php foreach ($block->getItemOptions() as $option) : ?>
                                    <dt><strong><em><?= $block->escapeHtml($option['label']) ?></em></strong></dt>
                                    <dd style="margin-left: 0; text-align:left;">
                                        <?= /* @noEscape */  nl2br($block->escapeHtml($option['value'])) ?>
                                    </dd>
                                <?php endforeach; ?>  
                                </dl> 
                            <?php endif; ?>
                            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                            <?php if ($addInfoBlock) :?>
                                <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                            <?php endif; ?> 
                            <?= $block->escapeHtml($_item->getDescription()) ?>
                            </div>
                    </td>
                </tr>
        </table>
        
        



    </td>
    <td class="item-qty" style="
    text-align: center;
"><?= (float) $_item->getQtyOrdered() ?></td> 
    <td class="item-price"style="text-align: right; width:45%;" > 
       
       <?= /* @noEscape */ $block->getItemPrice($_item) ?>

    </td> 

<?php if ($_item->getGiftMessageId()
    && $_giftMessage = $this->helper(\Magento\GiftMessage\Helper\Message::class)
        ->getGiftMessage($_item->getGiftMessageId())
) : ?>
   
        <table class="message-gift">
            <tr>
                <td>
                    <h3><?= $block->escapeHtml(__('Gift Message')) ?></h3>
                    <strong><?= $block->escapeHtml(__('From:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                    <br /><strong><?= $block->escapeHtml(__('To:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                    <br /><strong><?= $block->escapeHtml(__('Message:')) ?></strong>
                    <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                </td>
            </tr>
        </table>
  
<?php endif; ?>
