<?php

/** @var \V4U\GST\Block\Adminhtml\GSTNumber $block */ ?>
<div class="admin__field field-comment">
    <label for="company_name" class="admin__field-label"><span><?= __('Company Name') ?></span></label>
    <div class="admin__field-control">
        <input
            id="company_name"
            name="company_name"
            class="admin__control-input">
    </div>
</div>

<div class="admin__field field-comment">
    <label for="gst_number" class="admin__field-label"><span><?= __('GST Number') ?></span></label>
    <div class="admin__field-control">
        <input
            id="gst_number"
            name="gst_number"
            class="admin__control-input">
    </div>
</div>