<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>
<div class="col-md-5">
	<div class="row">	
	<a class="product-item-photo" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($item) ?>" title="<?php echo $block->escapeHtml($product->getName()) ?>">
		 <?php 
		 $productImage = $block->getImage($product, 'hot_product_page_image_medium'); ?>
				<img src="<?php /* @escapeNotVerified */ echo $productImage->getImageUrl(); ?>" class="img-responsive">
		 </a>
	</div>
</div>
  

