<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Cart $block */
// @codingStandardsIgnoreFile

/* @var \Magento\Wishlist\Model\Item $item */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$item = $block->getItem();
$product = $item->getProduct();

?>
<div class="product-price">
<?php
if( $product->getData('price_on_request') ) {
    ?>
    <span class="price-container">
        <span class="price"><?php /* @escapeNotVerified */ echo __('Price on request') ?></span>        
    </span>
    <?php
}else{
     foreach ($block->getChildNames() as $childName): ?>
    <?php /* @escapeNotVerified */ echo $block->getLayout()->renderElement($childName, false); ?>
   <?php endforeach;
}
?>
</div>