<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$currentPageUrl=$this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);
?>
<div class="model_wrapper" style="display:none">
<div id="ENQPopup" class="modal-form" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content-popup">
            <div class="custom-modal-header">
                <button type="button" class="close" data-role="action" data-dismiss="modal">×</button>
            </div>
            <div class="modal-body">
                <div class="col-md-7 col-xs-12">
                    <form class="form quickrfq"
                          action="/quickrfq/index/post/"
                          id="quickrfq_form"
                          enctype="multipart/form-data"
                          method="post"
                         
                          data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
                          data-mage-init='{"validation":{}}'>
                                                    
                                                    
                        <fieldset class="fieldset">
                            <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Enquire') ?></span></legend><br />

                            <div class="row">
                                <div class="form-group col-md-6 field name required">
                                    <label class="label" for="first_name"><?php echo __('First Name') ?></label>
                                    <div class="control">
                                                <input name="company" id="company" title="<?php /* @escapeNotVerified */ echo __('First Name') ?>" value="" class="input-text" type="text" data-validate="{required:true}"/>
                                    </div>
                                </div>
                                <div class="form-group col-md-6 field last required">
                                    <label class="label" for="last_name"><?php echo __('Last Name') ?></label>
                                    <div class="control">
                                                <input name="contact_name" id="contact_name" title="<?php /* @escapeNotVerified */ echo __('Last Name') ?>" value="" class="input-text" type="text" data-validate="{required:true}"/>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group field email required">
                                <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
                                <div class="control">
                                    <input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-3 field code">
                                    <label class="label" for="country_code"><span><?php /* @escapeNotVerified */ echo __('Code') ?></span></label>
                                    <div class="control">
                                        <input name="country_code" id="country_code" title="<?php /* @escapeNotVerified */ echo __('Code') ?>" maxlength="3"  placeholder="<?php /* @escapeNotVerified */ echo __('+91') ?>" value="" class="input-text" type="text"/>
                                    </div>
                                </div>
                                <div class="form-group col-md-9 field phone">
                                    <label class="label" for="phone"><span><?php /* @escapeNotVerified */ echo __('Your Mobile Number') ?></span></label>
                                    <div class="control">
                                        <input name="phone" id="phone" title="<?php /* @escapeNotVerified */ echo __('Mobile Number') ?>"  placeholder="<?php /* @escapeNotVerified */ echo __('Enter Your Number') ?>" value="" class="input-text" type="text" data-validate="{required:true}"/>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="label" for="message"><span><?php /* @escapeNotVerified */ echo __('Your Message') ?></span></label>
                                <div class="control">
                                    <textarea name="overview" id="overview" title="<?php /* @escapeNotVerified */ echo __('Your Message') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
                                </div>
                            </div>



                            <input name="project_title" id="current_url"  value="<?php /* @escapeNotVerified */ echo $currentPageUrl;?>" type="hidden" />
                            
                            <div class="field">
                                    
                                   
                                           <!-- <div class="g-recaptcha"  name="recaptcha" id="recaptcha" data-sitekey="6LcwlVgkAAAAAErxXu6IpBEgLzLq8PZgQt5xnAS2"></div> -->
                                        
                                            
                                             
                                    
                            </div>
                            
                            
                           
                            
                            <?php echo $block->getChildHtml('form.additional.info'); ?>
                        </fieldset>
                        <div class="actions-toolbar">
                            <div class="primary">
                                <input type="hidden" name="hideit" id="hideit" value="" />
                                <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit primary">
                                    <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
                                </button>
                            </div>
                        </div>
                    </form>
                    </div>
                    <div class="col-md-5 col-xs-12">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('rmipopup')->toHtml();?>
                            </div>
            </div>
        </div>
    </div>

</div>
</div>
<script type="text/javascript">
    function myFunction2() {
        var exists = document.getElementById("g-recaptcha-response");

            if(exists == null){
                    
            }
        
             else{

            var check = document.getElementById("g-recaptcha-response").value;
           // alert(check);
                if(check=='' || check == null){
                    document.getElementById("recaptcha").style.border = "1px solid #ea0e0e";
                    return false;
                }
                else{
                    document.getElementById("recaptcha").style.border = "none";
                    return true;
                }
            }
            
   
}
</script>


<style type="text/css">
    
    #recaptcha {
  display: inline-block;
  position: relative;
  
  
}

body.ox_quickview-catalog_product-view iframe {
    display: none !important;
}

</style>

<script type="text/javascript">
    require([
        "jquery",
        "Magento_Ui/js/modal/modal"
    ],function($, modal) {

        var options = {
            type: 'popup',
            responsive: true,
            modalClass: 'custom-popup-form enquiry-form',
            //title: 'Main title',
            buttons: [{
                text: $.mage.__('Cancel'),
                class: '',
                click: function () {
                    var element = document.getElementById("ENQPopup");
                    element.querySelector("span").textContent = 'ENQUIRE';
                    this.closeModal();
                }
            }]
        };

        $(".enq_popup_anchor").click(function() {
            var datatarget = $(this).attr('data-target');
            var popup = modal(options, $(datatarget));
            $(datatarget).modal('openModal');
            $(".modal-footer").remove();
            $(".modal-header").remove();
            return false;
        });
    });
</script>
<script type="text/javascript">
        function changePopupTitle() {
            var newPageTitle = document.getElementById("customPopupTitle").textContent;
           // newPageTitle = x.querySelector("a").textContent;
            var y = document.getElementById("ENQPopup");
            y.querySelector("span").textContent = newPageTitle;
        }
        function changeMakersPopupTitle() {
            newPageTitle = 'Connect with us';
            var x = document.getElementById("ENQPopup");
            x.querySelector("span").textContent = newPageTitle;
        }
        function changeGetInTouchTitle() {
            newPageTitle = 'GET IN TOUCH';
            var x = document.getElementById("ENQPopup");
            x.querySelector("span").textContent = newPageTitle;
        }
    </script>