<style>
    #popup-form {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.5);
        display: flex;
        justify-content: center;
        align-items: center;
        z-index: 1000;
    }

    .popup-content {
        position: relative;
        background-color: white;
        padding: 20px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
        width: 50%;
    }

    #popup-form div {
        margin-bottom: 10px;
    }

    #popup-form button {
        padding: 10px 20px;
        background-color: #333;
        color: white;
        border: none;
        cursor: pointer;
    }

    .close {
        position: absolute;
        top: 10px;
        right: 20px;
        font-size: 30px;
        font-weight: bold;
        color: #aaa;
        cursor: pointer;
    }

    .close:hover,
    .close:focus {
        color: #000;
        text-decoration: none;
        cursor: pointer;
    }

    .popup-content {
        max-width: 980px;
        display: flex;
        width: 100%;
        padding: 0px;
        outline: 1px solid #ccc;
        background-color: #f0f0f0;
    }

    form#notify_form input {
        background: transparent;
        height: 51.59px !important;
        background: #f0f0f0 !important;
        padding: 0 20px;
        font-family: 'Futura-bk-bt-book' !important;
        padding: 0 10px;
        border: #ddd 1px solid;
    }

    form#notify_form input[type=checkbox]{
    height: 12px ! IMPORTANT;
    margin-right: 0px;
    position: static;
}

    .left_image {
        min-width: 50%;
        margin-bottom: 0px !important;
    }

    .left_image img {
        width: 100%;
        height: 100%;
        object-fit: cover;
    }

    .frm_wrap {
        padding: 30px;
        margin-bottom: 0px !important;
    }

    .frm_wrap h2 {

        font-family: 'Futura-lt-bt light';
        font-size: 27.25px;
        text-align: center;
    }

    .frm_wrap h2+p {
        font-family: 'botoni-bk-bt' !important;
        font-weight: 400 !important;
        font-size: 20px;
        text-align: center;
    }

    #popup-form #notify_submit {
        max-width: 100%;
        height: 51.59px;
        color: #f0f0f0 !important;
        font-family: 'Futura-lt-bt light' !important;
        font-size: 24px;
        letter-spacing: 2px;
        width: 100%;
    }

    form#notify_form {
        margin: 45px 0 0 0;
    }

    .sign-up p {
        text-align: center;
        padding: 0 25px;
        margin: 50px 0 0 0;
        font-family: 'Futura-bk-bt-book';
        font-size: 13px;
        color: #2d2d2d;
        letter-spacing: 1px;
    }

    #popup-form .close {
        color: #000;
    }

    .modal-popup .modal-header h1 {
        font-weight: 500;
        letter-spacing: 1.62px;
        line-height: 19px;
        font-family: 'Futura-lt-bt light' !important;
        font-size: 27.25px;
    }

    .modal-popup.confirm .modal-inner-wrap {
        background-color: #f0f0f0;
    }

    .modal-popup>.modal-inner-wrap>.modal-content {
        padding: 10px 30px;
        font-weight: 400 !important;
        font-size: 20px;
        text-align: center;
        font-style: italic;
        line-height: 34px;
        font-family: "Cormorant Garamond", serif !important;
    }

    .modal-popup._show,
    .modal-slide._show {
        top: 25%;
    }

    @media screen and (max-width:767px) {
        #popup-form .popup-content {
            display: block;
            margin: auto;

        }

        .frm_wrap {
            padding: 10px;
        }

        form#notify_form {
            margin: 20px 0 0 0;
        }

        .frm_wrap h2+p {
            font-size: 15px;
            line-height: normal;
        }

        form#notify_form input,
        #popup-form #notify_submit {
            height: 40px !important;
            font-size: 15px;
            letter-spacing: 0px;
        }

        .frm_wrap h2 {
            font-size: 20px;
            margin-top: 10px;
        }

        .sign-up p {
            letter-spacing: 0px;
            font-size: 11px;
        }


        .modal-popup>.modal-inner-wrap>.modal-content {
            font-size: 20px;
            padding: 30px 20px 10px 20px;
            line-height: 27px;
        }

        .modal-popup .modal-header h1 {
            font-size: 20px;
            line-height: 27px;
            text-align: center;
        }

        .modal-popup .modal-header {
            padding-bottom: 10px;
            padding-top: 20px;
        }

        .left_image {
            display: none;
        }

        .modal-popup .modal-inner-wrap {
            width: 95%;
        }
    }
</style>
<div id="popup-form" style="display:none;">
    <div class="popup-frm-wrap">

        <div class="popup-content">
            <div class="left_image">
                <img src="pub/media/popup-img.jpg" />
            </div>
            <div class="frm_wrap">
                <span id="close-popup" class="close">&times;</span>
                <div>
                    <h2>BE IN THE KNOW!
                        <hr class="hr--small">
                    </h2>
                    <p>The House of Things is a curated online destination
                        to discover and shop for luxury interiors.
                    </p>
                </div>
                <form method="post" id="notify_form">
                    <div>
                        <input type="text" placeholder="Name" name="notify_name" id="notify_name" required />
                    </div>
                    <div>
                        <input type="text" placeholder="Mobile Number" name="notify_number" id="notify_number" required />
                    </div>
                    <div>
                        <input type="email" placeholder="Email Address" name="notify_email" id="notify_email" required />
                    </div>
                    <div>
                        <input type="checkbox" name="notify_checkbox" id="notify_checkbox" value="1" required />
                        Sign up and be the first to know about new arrivals and latest offers, delivered straight to your inbox.
                    </div>
                    <div>
                        <button type="submit" <?php echo (isset($_COOKIE['formSubmitted']) && $_COOKIE['formSubmitted'] == true) ? "disabled='true'" : ""; ?> id="notify_submit">Submit</button>
                    </div>
                    <div class="sign-up">
                        <p>Sign up and be the first to know about latest collections at
                            The House Of Things, delivered staright to your inbox.
                        </p>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>