
<?php $helper = $this->helper('Magento\Search\Helper\Data'); ?>

    <div class="toggle-example">
        <div class="toggle-wrap">
            <a href="#"
                data-mage-init='{"toggleAdvanced": {"selectorsToggleClass": "active", "baseToggleClass": "expanded", "toggleContainers": "#desktopSearchToggleContainer", "newLabel": "Search"}}'
                title="Search" class="action">Search</a>
        </div>
        <div class="toggle-container" id="desktopSearchToggleContainer">
        <a href="#"
                data-mage-init='{"toggleAdvanced": {"selectorsToggleClass": "active", "baseToggleClass": "expanded", "toggleContainers": "#desktopSearchToggleContainer", "newLabel": "Search"}}'
                title="Search" class="action remove-search">Search</a>
        
            <div class="search-container">
                <form class="form minisearch" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>"
                    method="get">

                    <div class="field search">
                        <span class="input-group-btn">
                            <button class="btn" type="submit" title="<?php echo $block->escapeHtml(__('Search')) ?>"
                                class="action search">
                                <span class="fa fa-search"></span>
                            </button>
                        </span>
                        <div class="control">
                            <input id="search" data-mage-init='{"quickSearch":{
                    "formSelector":"#search_mini_form",
                    "url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest', ['_secure' => $block->getRequest()->isSecure()]); ?>",
                    "destinationSelector":"#search_autocomplete"}
               }' type="text" name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
                                value="<?php /* @escapeNotVerified */ //echo $helper->getEscapedQueryText() ?>"
                                placeholder="<?php /* @escapeNotVerified */ echo __('What are you looking for?'); ?>"
                                class="search-query form-control"
                                maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
                                role="combobox" aria-haspopup="false" aria-autocomplete="both" autocomplete="off" />
                            <div id="search_autocomplete" class="search-autocomplete"></div>
                            <?php echo $block->getChildHtml() ?>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

