<div id="gst-number">
    <strong><?= __('GST Number') ?>:</strong>
    <br />
    <span class="price"><?= $block->getGstNumber() ?></span>
</div>
<div id="company-name">
    <strong><?= __('Company Name') ?>:</strong>
    <br />
    <span class="price"><?= $block->getCompanyName() ?></span>
</div>
<script type="text/javascript">
    require(
        ['jquery'],
        function($) {
            var element = $('#gst-number').detach();
            $('.box-order-shipping-method').append(element);

            var element2 = $('#company-name').detach();
            $('.box-order-shipping-method').append(element2);

        }
    );
</script>