<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');

$mediaPath=$storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA );


if($block->getCurrentBrand()->getData('is_profile_layout')):?>
<div class="row profile-layout-top">
	<div class="col-md-4">
		<?php if(!empty($block->getCurrentBrand()->getData('brand_logo'))):?>
			<img src="<?php echo $mediaPath.$block->getCurrentBrand()->getData('brand_logo')?>" class="img-responsive" />
		<?php endif;?>
	</div>
	<div class="col-md-8">
		<?php if ($_description = $block->getCurrentBrand()->getDescription()): ?>
			<div class="profile-layout-brand-description">
				<?php echo $this->helper('Ves\Brand\Helper\Data')->filter($_description) ?>
			</div>
		<?php endif; ?>
	</div>

<?php else :
	if(!empty($block->getCurrentBrand()->getData('brand_logo'))):?>
		<img src="<?php echo $mediaPath.$block->getCurrentBrand()->getData('brand_logo')?>" class="img-responsive" />
	<?php endif;?>
	<?php if ($_description = $block->getCurrentBrand()->getDescription()): ?>
		<div class="brand-description">
			<?php echo nl2br($this->helper('Ves\Brand\Helper\Data')->filter($_description)) ?>
		</div>
	<?php endif; ?>
<?php endif;?>
	<div class="clearfix"></div>
	<div class="btnViewAll text-center">
		<a href="#featuredProducts" class="btnStyle"><?php echo __('Shop The Maker')?></a>
	</div>
	<div class="clearfix"></div>