<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @see \Magento\AdminNotification\Block\Window
 */
?>
<ul class="message-system-list"
    style="display: none;"
    data-mage-init='{
        "Magento_Ui/js/modal/modal": {
            "autoOpen": true,
            "buttons": false,
            "modalClass": "modal-system-messages",
            "title": "<?= $block->escapeHtmlAttr($block->getHeaderText()) ?>"
        }
    }'>
    <li class="message message-warning warning">
        <?= $block->escapeHtml($block->getNoticeMessageText()) ?><br/>
        <a href="<?= $block->escapeUrl($block->getNoticeMessageUrl()) ?>" target="_blank">
            <?= $block->escapeHtml($block->getReadDetailsText()) ?>
        </a>
    </li>
    <li class="message message-warning warning">
        <?= $block->escapeHtml($block->getAdditionalTitle()) ?><br/>
        <a href="<?= $block->escapeUrl($block->getAdditionalLink()) ?>" target="_blank">
            <?= $block->escapeHtml($block->getReadDetailsText()) ?>
        </a>
    </li>
</ul>
