<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Onepage */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get(\Magento\Store\Model\StoreManagerInterface::class);
$currentStore = $storeManager->getStore();
$storeId = $currentStore->getId();
?>

<div id="single-checkout" data-bind="scope:'single-checkout'" class="single-checkout-page">
    <div id="checkout-loader" data-role="checkout-loader" class="loading-mask">
        <div class="loader">
            <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif')); ?>"
                alt="<?= $block->escapeHtml(__('Loading...')); ?>"
                style="position: absolute;">
        </div>
    </div>
    <div data-bind="css: { _disable_scroll: isLoading }" class="checkout-container">
        <script type="text/x-magento-init">
            {
                "#single-checkout": {
                    "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
                }
            }
        </script>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "single-checkout": {
                        "component": "uiComponent"
                    }
                }
            }
        }
    }
</script>