<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Sales\Block\Order\Totals
 * @see \Magento\Sales\Block\Order\Totals
 */
?>
<?php foreach ($block->getTotals() as $_code => $_total) :

    if (strpos($_total->getLabel(), "Shipping ") !== false) {
        continue;
    }

?>
    <?php if ($_total->getBlockName()) : ?>
        <div class="totoealds">
            <?= $block->getChildHtml($_total->getBlockName(), false) ?>
        </div>
    <?php else : ?>
        <tr class="<?= $block->escapeHtmlAttr($_code) ?> sjdjdjdjd">
            <td colspan="5">
                <table style="width:100%;">
                    <tr>
                        <th style="text-align: right;" <?= /* @noEscape */ $block->getLabelProperties() ?> scope="row">
                            <?php if ($_total->getStrong()) : ?>
                                <strong><?= $block->escapeHtml($_total->getLabel()) ?></strong>
                            <?php else : ?>
                                <?= $block->escapeHtml($_total->getLabel()) ?>
                            <?php endif ?>
                        </th>
                    </tr>
                    <tr>
                        <td style="text-align: right;" <?= /* @noEscape */ $block->getValueProperties() ?> data-th="<?= $block->escapeHtmlAttr($_total->getLabel()) ?>">
                            <?php if ($_total->getStrong()) : ?>
                                <strong><?= /* @noEscape */ $block->formatValue($_total) ?></strong>
                            <?php else : ?>
                                <?= /* @noEscape */ $block->formatValue($_total) ?>
                            <?php endif ?>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    <?php endif; ?>
<?php endforeach ?>