<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>

<div class="mobile-search-bar">

			<form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">

							<div class="field search">
								<span class="input-group-btn">
								<button class="btn" type="submit" title="<?php echo $block->escapeHtml(__('Search')) ?>" class="action search">
									<span class="fa fa-search"></span>
								</button>
							</span>
								<div class="control">
									<input id="search"
										   data-mage-init='{"quickSearch":{
												"formSelector":"#search_mini_form",
												"url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest', ['_secure' => $block->getRequest()->isSecure()]); ?>",
												"destinationSelector":"#search_autocomplete"}
										   }'
										   type="text"
										   name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
										   value="<?php /* @escapeNotVerified */ //echo $helper->getEscapedQueryText() ?>"
										   placeholder="<?php /* @escapeNotVerified */ echo __('What are you looking for?'); ?>"
										   class="search-query form-control"
										   maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
										   role="combobox"
										   aria-haspopup="false"
										   aria-autocomplete="both"
										   autocomplete="off"/>
										<div id="search_autocomplete" class="search-autocomplete"></div>
										<?php echo $block->getChildHtml() ?>
								</div>
							</div>
						</form>


</div>
<div id="TopnavSearch" class="modal fade in TopnavSearch-modal" role="dialog" >
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h2><?php /* @escapeNotVerified */ echo __('Search'); ?></h2>
				<button type="button" class="close" data-dismiss="modal">×</button>
			</div>
			<div class="modal-body">
				<div id="custom-search-input">
					<div class="input-group col-md-12">
						<form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
							<div class="field search">
								<div class="control">
									<input id="search"
										   data-mage-init='{"quickSearch":{
												"formSelector":"#search_mini_form",
												"url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest', ['_secure' => $block->getRequest()->isSecure()]); ?>",
												"destinationSelector":"#search_autocomplete"}
										   }'
										   type="text"
										   name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
										   value="<?php /* @escapeNotVerified */ //echo $helper->getEscapedQueryText() ?>"
										   placeholder="<?php /* @escapeNotVerified */ echo __('What are you looking for?'); ?>"
										   class="search-query form-control"
										   maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
										   role="combobox"
										   aria-haspopup="false"
										   aria-autocomplete="both"
										   autocomplete="off"/>
										<div id="search_autocomplete" class="search-autocomplete"></div>
										<?php echo $block->getChildHtml() ?>
								</div>
							</div>
							<span class="input-group-btn">
								<button class="btn" type="submit" title="<?php echo $block->escapeHtml(__('Search')) ?>" class="action search">
									<span class="fa fa-search"></span>
								</button>
							</span>
						</form>
				</div>
			</div>
		</div>
	</div>
</div>
</div>