<form action="<?= $block->getFormAction() ?>" method="post" enctype="multipart/form-data">
    <input type="hidden" name="form_key" value="<?= $block->getFormKey() ?>" />

    <div>
        <label for="name">Name:</label>
        <input type="text" name="name" id="name" value="<?php echo isset($_POST['name']) ? $_POST['name'] : ""  ?>" required />
    </div>

    <div>
        <label for="email">Email:</label>
        <input type="email" name="email" id="email" required />
    </div>

    <div>
        <label for="phone">Phone:</label>
        <input type="text" name="phone" id="phone" required />
    </div>

    <div>
        <label for="message">Message:</label>
        <textarea name="message" id="message" required></textarea>
    </div>

    <div>
        <label for="file">File:</label>
        <input type="file" name="catalog" id="catalog" />
    </div>

    <div>
        <button type="submit">Submit</button>
    </div>
</form>
<script type="text/javascript">
    require(['DiMedia_Collaboration/js/form-validation'], function(formValidation) {
        formValidation();
    });
</script>