<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\Contact\Block\ContactForm $block */
/** @var \Magento\Contact\ViewModel\UserDataProvider $viewModel */

$viewModel = $block->getViewModel(); 
?>
<form class="form contact"
    action="<?php echo $block->escapeUrl($block->getUrl('collaboration/index/submit')) ?>"
    id="contact-form"
    method="post"
    data-hasrequired="<?php echo $block->escapeHtmlAttr(__('* Required Fields')) ?>"
    data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend">
            <h3><span><?php echo $block->escapeHtml(__('ENQUIRIES')) ?></span></h3>
        </legend><br />
        <div class="row  select-enquiry">
            <div class="field first_name name required col-md-12">
                <input type="hidden" name="hideit" id="hideit" value="th_vali" class="hideit" />
                <!-- <div class="control">
                    <select name="query_about" id="query_about" data-validate="{required:true}">
                        <option value="Concierge">Concierge</option>
                        <option value="Interior Design Services">Interior Design Services</option>
                        <option value="Trade">Trade</option>
                        <option value="Gifting">Gifting</option>
                        <option value="Others">Others</option>
                    </select>
                </div> -->
            </div>
        </div>
        <div class="row name-co">
            <div class="field first_name name required col-md-12">
                <label class="label" for="name"><span><?php echo $block->escapeHtml(__('Name')) ?></span></label>
                <div class="control">
                    <input name="name"
                        id="name"
                        title="<?php echo $block->escapeHtmlAttr(__('Name')) ?>"
                        placeholder="<?php echo $block->escapeHtmlAttr(__('Name')) ?>"
                        value="<?php echo $block->escapeHtmlAttr($viewModel->getUserName()) ?>"
                        class="input-text"
                        type="text"
                        data-validate="{required:true}" />
                </div>
            </div>
            
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?php echo $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input name="email"
                    id="email"
                    title="<?php echo $block->escapeHtmlAttr(__('Email')) ?>"
                    value="<?php echo $block->escapeHtmlAttr($viewModel->getUserEmail()) ?>"
                    class="input-text"
                    type="email"
                    data-validate="{required:true, 'validate-email':true}"
                    data-mage-init='{"mage/trim-input":{}}' />
            </div>
        </div>
        <div class="row telephone">
            <div class="field country_code col-md-3">
                <label class="label" for="country_code"><span><?php echo $block->escapeHtml(__('Code')) ?></span></label>
                <div class="control">
                    <input name="country_code"
                        id="country_code"
                        title="<?php echo $block->escapeHtmlAttr(__('+91')) ?>"
                        placeholder="<?php echo $block->escapeHtmlAttr(__('+91')) ?>"
                        value=""
                        class="input-text"
                        type="tel" />
                </div>
            </div>
            <div class="field telephone col-md-9">
                <label class="label" for="telephone"><span><?php echo $block->escapeHtml(__('Mobile Number')) ?></span></label>
                <div class="control">
                    <input name="phone"
                        id="telephone"
                        title="<?php echo $block->escapeHtmlAttr(__('Mobile Number')) ?>"
                        value="<?php echo $block->escapeHtmlAttr($viewModel->getUserTelephone()) ?>"
                        class="input-text"
                        type="tel" />
                </div>
            </div>
        </div>
        <div class="field comment required">
            <label class="label" for="comment">
                <span><?php echo $block->escapeHtml(__('Message')) ?></span>
            </label>
            <div class="control">
                <textarea name="comment"
                    id="comment"
                    title="<?php echo $block->escapeHtmlAttr(__('What’s on your mind?')) ?>"
                    class="input-text"
                    cols="5"
                    rows="3"
                    data-validate="{required:true}"><?php echo $block->escapeHtml($viewModel->getUserComment()) ?></textarea>
            </div>
        </div>
        <?php echo $block->getChildHtml('form.additional.info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?php echo $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?php echo $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "contact-form"
            }
        }
    }
</script>