<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View
 */
?>
<?php $_helper = $this->helper(Magento\Catalog\Helper\Output::class); ?>
<?php $_product = $block->getProduct(); ?>

<?php
$new_layout = array(137);
$categories = $_product->getCategoryIds();
$result = array_intersect($new_layout, $categories);
if (empty($result)) { ?>
    <div class="product-add-form">
        <form action="<?php /* @escapeNotVerified */ echo $block->getSubmitUrl($_product) ?>" method="post"
            id="product_addtocart_form" <?php if ($_product->getOptions()): ?> enctype="multipart/form-data" <?php endif; ?>>
            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $_product->getId() ?>" />
            <input type="hidden" name="selected_configurable_option" value="" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
            <?php echo $block->getBlockHtml('formkey') ?>
            <?php echo $block->getChildHtml('form_top'); ?>
            <?php if (!$block->hasOptions()): ?>
                <?php echo $block->getChildHtml('product_info_form_content'); ?>
            <?php else: ?>
                <?php
                //$_product->isSaleable() &&
                if ($block->getOptionsContainer() == 'container1'): ?>
                    <?php echo $block->getChildChildHtml('options_container') ?>
                <?php endif; ?>
            <?php endif; ?>

            <?php
            //$_product->isSaleable() && 
            if ($block->hasOptions() && $block->getOptionsContainer() == 'container2'): ?>
                <?php echo $block->getChildChildHtml('options_container') ?>
            <?php endif; ?>
            <?php echo $block->getChildHtml('form_bottom'); ?>
        </form>
    </div>
    <script>
        require(['jquery', 'Magento_Catalog/js/price-box'], function($) {
            var priceBoxes = $('.product-info-price [data-role=priceBox]');
            priceBoxes = priceBoxes.filter(function(index, elem) {
                return !$(elem).find('.price-from').length;
            });

            priceBoxes.priceBox({
                'priceConfig': <?php echo $block->getJsonConfig(); ?>
            });
        });
    </script>
<?php } ?>