<?php

/**
 * @category Mageants GiftCard
 * @package Mageants_GiftCard
 * @copyright Copyright (c) 2016 Mageants
 * @author Mageants Team <support@mageants.com>
 */

/** @var $block \Magento\Sales\Block\Order\Totals */

$giftValue = $block->getOrder()->getOrderGift();
$flag = false;
$viewModel = $block->getData("viewModel");
$currencyCode = $block->getOrder()->getOrderCurrencyCode();
$currencySymbol = $viewModel->getCurrencySymbol($currencyCode);
?>

<?php foreach ($block->getTotals() as $_code => $_total): ?>
    <?php if ($_total->getBlockName()): ?>
        <?= /* @noEscape */ $block->getChildHtml($_total->getBlockName(), false); ?>
    <?php else: ?>
        
        <tr class="<?= /* @noEscape */ $_code ?>">
            <th <?= /* @noEscape */ $block->getLabelProperties() ?> scope="row">
                <?php if ($_total->getStrong()): ?>
                    <strong><?= /* @noEscape */ $block->escapeHtml($_total->getLabel()); ?></strong>
                <?php else: ?>
                    <?= /* @noEscape */ $block->escapeHtml($_total->getLabel()); ?>
                <?php endif ?>
            </th>
            <td <?= /* @noEscape */ $block->getValueProperties() ?>
                data-th="<?= /* @noEscape */ $block->escapeHtml($_total->getLabel()); ?>">
                <?php if ($_total->getStrong()): ?>
                    <strong><?= /* @noEscape */ $block->formatValue($_total) ?></strong>
                <?php else: ?>
                    <?= /* @noEscape */ $block->formatValue($_total) ?>
                <?php endif ?>
                <?php if ($giftValue && !$_total->getLabel()): ?>
                    <?= /* @noEscape */ __($giftValue); ?>
                <?php endif; ?>
            </td>
            <?php if (!$flag) { ?>
        <tr class="<?= /* @noEscape */ $_code ?>">
            <th <?= /* @noEscape */ $block->getLabelProperties() ?> scope="row">
                <?php if ($giftValue): ?>
                    <?= /* @noEscape */ __('Gift Card'); ?>
                <?php endif; ?>
            </th>
            <td <?= /* @noEscape */ $block->getValueProperties() ?>>
                <?php if ($giftValue): ?>
                    <?= /* @noEscape */ __($currencySymbol . round($giftValue, 2)); ?>
                <?php endif; ?>
            </td>
        </tr>
        <?php $flag = true; ?>
        </tr>
    <?php } ?>
<?php endif ?>
<?php endforeach ?>