<?php
$brandCollection = $this->getBrandCollection();

$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$_imageHelper = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Catalog\Helper\Image');
$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
$blockObj= $block->getLayout()->createBlock('Magento\Catalog\Block\Product\View');
$connection = $resource->getConnection();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$mediaPath=$storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA );
$data = $this->helper('Ves\Brand\Helper\Data');
$brand_layout_listing = $data->getConfig("product_view_page/brand_layout_listing");
$show_brand_text = $data->getConfig("product_view_page/show_brand_text");
$brand_text = $data->getConfig("product_view_page/brand_text");
$brand_text = $brand_text?$brand_text:__('Brands: ');
$show_brand_image = $data->getConfig("product_view_page/show_brand_image");
$show_brand_name = $data->getConfig("product_view_page/show_brand_name");

?>
<?php if($brandCollection && $brandCollection->count()){ ?>
	<?php 
		foreach ($brandCollection as $_brand) {?>
	<section class="bg-white">
		<div class="container ">
			 <div class="about-maker"> 
			<?php if($show_brand_image): ?>
				<div class="col-md-3">
					<div class="row">
					<?php 
					// checking logo profile layout 0=> brand logo 1=> profile picture
					  if(!$_brand->getIsProfileLayout()) {
						  ?>
						  <div class="brandlogo">
						  <a href="<?php echo $_brand->getUrl(); ?>" title="<?php echo $_brand->getName(); ?>">
						  <img src="<?php echo $mediaPath.$_brand->getBrandLogo(); ?>" class="img-responsive" alt="<?php echo $_brand->getName(); ?>" alt="<?php echo $_brand->getName(); ?>"/></a>
						  </div>
						  <?php
						  
					  }else {
					?>
						<a href="<?php echo $_brand->getUrl(); ?>" title="<?php echo $_brand->getName(); ?>">
						<img src="<?php echo $mediaPath.$_brand->getBrandLogo(); ?>" class="img-responsive" alt="<?php echo $_brand->getName(); ?>" alt="<?php echo $_brand->getName(); ?>"/></a>
					<?php }?>
					</div>	
				</div>
				<?php endif; ?>
				<div class="col-md-9 middle-text">
					<?php if($show_brand_name): ?>
					<h3>The Maker</h3>
					<h4 class="bd-name"><a href="<?php echo $_brand->getUrl(); ?>" title="<?php echo $_brand->getName(); ?>"><?php echo $_brand->getName(); ?></a></h4>
					<?php endif; ?>
					<p><?php echo $this->helper('Ves\Brand\Helper\Data')->filter($_brand->getDescription()) ?></p>
					<a href="<?php echo $_brand->getUrl(); ?>" class="btnStyle">View more details</a>
				</div>
			</div> 
			
			<div class="clearfix"></div>
		</div>
	</section>


<?php 
$brand =  $_brand->getID();
	if( !empty($brand) ){
     $sql = "SELECT DISTINCT ccp.product_id FROM catalog_category_product ccp
       left join catalog_product_entity_varchar  as cpei on cpei.entity_id=ccp.product_id and cpei.attribute_id=210
       left join catalog_product_entity_int as cpei1 on cpei1.entity_id=ccp.product_id and cpei1.attribute_id=97
       left join catalog_product_entity_int as cpei2 on cpei2.entity_id=ccp.product_id and cpei2.attribute_id=99
       WHERE cpei.value = ". $brand ." AND cpei1.value = 1 AND cpei2.value = 4 AND ccp.product_id <> ".$product->getId(). " ORDER BY RAND() LIMIT 4";
	if( !empty($connection->fetchAll($sql)) ){
		$results1 = $connection->fetchAll($sql);
				$webpImageDataHelper = $this->helper('DiMedia\WebpImage\Helper\Data');
		 // print_r($results1 );
		 // die();
		?>
		<section class="bg-white similar-products custom-data">
			<div class="container">
			   <div class="row"> 
				   <div class="section-header text-center">
					  <div class="sectionTitle">More From This Maker</div>
					  <hr class="hr--small">
				   </div>
					   <?php
						foreach ( $results1 as $key => $productid ) {
							$_item = $objectManager->create('Magento\Catalog\Model\Product')->load($productid['product_id']);
							$resizedImageUrl = $_imageHelper->init($_item, 'product_page_related_images')->getUrl();
							 $resizedImageUrl = $webpImageDataHelper->getWebpUrl($resizedImageUrl);
							?>
							<div class="col-md-3 col-sm-3 col-xs-12">
								  <div class="thumbnail" >
									 <a href="<?php echo $_item->getProductUrl() ?>" class="">
				                        <?php  echo '<img src="'.$resizedImageUrl.'" class="img-responsive">';;
										?>
									</a>
									 <div class="caption">
										<div class="row">
										   <div class="col-md-7 col-xs-7">
											  <div class="custom-row">
												 <h3 class="productName">
													<a class="" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>">
													<?php echo $_item->getName(); ?></a>
												</h3>
											  </div>
										   </div>
										   <div class="col-md-5 col-xs-5 price">
											  <div class="custom-row">
											  	<div class="productPrice"><?php echo $blockObj->getProductPrice($_item); ?></div>
											  </div>
										   </div>
										</div>
										<div class="custom-row">
										   <p class="productDetail"> 
												<?php 
												$tableName = $resource->getTableName('ves_brand_product');
												$sql = "select brand_id FROM " . $tableName." Where product_id =".$_item->getID();
												$connection2 = $resource->getConnection();
												if(!empty($connection2->fetchAll($sql))){
													$brand_id = $connection2->fetchAll($sql)[0]['brand_id'];
													$tableName = $resource->getTableName('ves_brand');
													$sql = "select name,url_key FROM " . $tableName." Where brand_id =".$brand_id;
													$brand_name = $connection2->query($sql);
													$res = $connection2->fetchAll($sql);
													echo 'By <a href='.$block->getBaseUrl().'makers/'.$res[0]['url_key'].'.html'.' title="'.$res[0]['name'].'">'.$res[0]['name'].'</a>';
												}
												?></p>
										</div>
										<div class="custom-row">
											<?php 
											// if ($_product->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE) {
											// echo '<span class="btnGrey">'.__('Options Available').'</span> ';
											// } 
											if($_item->getAttributeText('options_available')=='Yes'){
												echo '<span class="btnGrey">'.__('Options Available').'</span>';
											}
											
											if($_item->getAttributeText('is_customizable')=='Yes'){
												echo '<span class="btnBlack">'.__('Customizable').'</span>';
											}
										 ?>
											</div>
									 </div>
								  </div>
							   </div>
							<?php

						}
						?>
		        </div>
			</div>
		</section>
	<?php
	}
}
		 }
	?>
<?php } ?>