<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * @category   BSS
 * @package    Bss_GA4
 * @author     Extension Team
 * @copyright  Copyright (c) 2022-2023 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
/**
 * Override core
 * Template for displaying new products widget
 *
 * @var $block \Bss\GA4\Block\Product\Widget\NewWidget
 */

// phpcs:disable Magento2.Files.LineLength.MaxExceeded
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
    $type = 'widget-new-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $title = __('New Products');
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
    $index = $block->getIndex();
    $gtag = $block->prepareListItems($block->getProductCollection());
}
?>

<?php if ($exist) :?>
    <div class="block widget block-new-products <?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $index?>">
        <div class="block-title">
            <strong role="heading" aria-level="2"><?= $block->escapeHtml($title) ?></strong>
        </div>
        <div class="block-content">
            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
            <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                <ol class="product-items <?= /* @noEscape */ $type ?>">
                    <?php foreach ($items as $_item) :?>
                        <li class="product-item">
                            <div class="product-item-info">
                                <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                   class="product-item-photo">
                                    <?= $block->getImage($_item, $image)->toHtml() ?>
                                </a>
                                <div class="product-item-details">
                                    <strong class="product-item-name">
                                        <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                           href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                           class="product-item-link">
                                            <?= $block->escapeHtml($_item->getName()) ?>
                                        </a>
                                    </strong>
                                    <?= $block->getProductPriceHtml($_item, $type); ?>

                                    <?php if ($templateType) :?>
                                        <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                    <?php endif; ?>

                                    <?php if ($showWishlist || $showCompare || $showCart) :?>
                                        <div class="product-item-actions">
                                            <?php if ($showCart) :?>
                                                <div class="actions-primary">
                                                    <?php if ($_item->isSaleable()) :?>
                                                        <?php if (!$_item->getTypeInstance()->isPossibleBuyFromList($_item)) :?>
                                                            <button class="action tocart primary"
                                                                    data-mage-init='{"redirectUrl":{"url":"<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}'
                                                                    type="button"
                                                                    title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                            </button>
                                                        <?php else :?>
                                                            <?php
                                                            $postDataHelper = $this->helper(Magento\Framework\Data\Helper\PostHelper::class);
                                                            $postData = $postDataHelper->getPostData(
                                                                $block->escapeUrl($block->getAddToCartUrl($_item)),
                                                                ['product' => (int) $_item->getEntityId()]
                                                            )
                                                            ?>
                                                            <button class="action tocart primary"
                                                                    data-post='<?= /* @noEscape */ $postData ?>'
                                                                    type="button"
                                                                    title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                            </button>
                                                        <?php endif; ?>
                                                    <?php else :?>
                                                        <?php if ($_item->isAvailable()) :?>
                                                            <div class="stock available">
                                                                <span><?= $block->escapeHtml(__('In stock')) ?></span>
                                                            </div>
                                                        <?php else :?>
                                                            <div class="stock unavailable">
                                                                <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                                            </div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                            <?php if ($showWishlist || $showCompare) :?>
                                                <div class="actions-secondary" data-role="add-to-links">
                                                    <?php if ($this->helper(Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist) :?>
                                                        <a href="#"
                                                           data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>'
                                                           class="action towishlist"
                                                           data-action="add-to-wishlist"
                                                           title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                    <?php if ($block->getAddToCompareUrl() && $showCompare) :?>
                                                        <?php $compareHelper = $this->helper(Magento\Catalog\Helper\Product\Compare::class);?>
                                                        <a href="#" class="action tocompare"
                                                           data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>'
                                                           title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </li>
                    <?php endforeach ?>
                </ol>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
        <?php if ($block->isEnableModule()):?>
            <script>
                require([
                    'jquery'
                ], function ($) {
                    'use strict';

                    window.addEventListener("load", (event) => {
                        createObserver();
                    }, false);

                    function createObserver() {
                        const options = {
                            root: null,
                            rootMargin: "0px",
                            threshold: 0.5
                        }
                        let index = <?=$block->serializer($index)?>;
                        let mode = <?=$block->serializer($mode)?>;
                        let script = '<script class="bss-view-list ' + index +'"> gtag("event", "view_item_list", {"item_list_id": "", "item_list_name": "","items":';
                        script += JSON.stringify(<?=$gtag?>);
                        script += "});</" + "script>";
                        let targets = $('.widget.block-new-products' + '.' + mode + '.' + index);
                        const onIntersect = (entries) => {
                            entries.forEach(entry => {
                                if (entry.intersectionRatio > 0) {
                                    let scriptViewList = $('.bss-view-list.' + index);
                                    if (scriptViewList.length === 0 ) {
                                        $('.bss-script').each(function( target, value ) {
                                            $(value).append(script);
                                        });
                                    }
                                }
                            });
                        }
                        let observer = new IntersectionObserver(onIntersect, options);
                        targets.each(function( target, value ) {
                            observer.observe(value)
                        });
                    }
                });
            </script>
        <?php endif;?>
    </div>
<?php endif;?>
